python ./colorize.py -img_in ../../CV_finalproject/data/Real/TL0.bmp -img_out ./color/TL0.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TL1.bmp -img_out ./color/TL1.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TL2.bmp -img_out ./color/TL2.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TL3.bmp -img_out ./color/TL3.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TL4.bmp -img_out ./color/TL4.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TL5.bmp -img_out ./color/TL5.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TL6.bmp -img_out ./color/TL6.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TL7.bmp -img_out ./color/TL7.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TL8.bmp -img_out ./color/TL8.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TL9.bmp -img_out ./color/TL9.png

python ./colorize.py -img_in ../../CV_finalproject/data/Real/TR0.bmp -img_out ./color/TR0.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TR1.bmp -img_out ./color/TR1.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TR2.bmp -img_out ./color/TR2.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TR3.bmp -img_out ./color/TR3.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TR4.bmp -img_out ./color/TR4.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TR5.bmp -img_out ./color/TR5.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TR6.bmp -img_out ./color/TR6.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TR7.bmp -img_out ./color/TR7.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TR8.bmp -img_out ./color/TR8.png
python ./colorize.py -img_in ../../CV_finalproject/data/Real/TR9.bmp -img_out ./color/TR9.png
